Better Docs
OIVAS7572/lichess-bot pull request #27
Opened 2021-06-23 04:57 UTC by lidevelopers

Better instructions about deploying the bot to heroku

2021-06-23 05:40 UTC, OIVAS7572 requested changes
Don't enable Automatic Deploys. Some Big files are downloading while deploying. Some times It will not work because of Over using resources.
Branch will be master not main.

2021-06-23 05:48 UTC, lidevelopers commented
now is it ok?

2021-06-23 06:30 UTC, OIVAS7572 commented on README.md
> +- You're now connected to lichess and awaiting challenges! Your bot is up and ready!
what you mean by 21 st line . This is showed in logs

2021-06-23 06:30 UTC, OIVAS7572 commented
@lidevelopers 
what you mean by 21 st line . This is showed in logs

2021-06-23 06:40 UTC, OIVAS7572 approved these changes

2021-06-23 06:43 UTC, lidevelopers commented
Are you merging

2021-06-23 08:06 UTC, TheYoBots commented
I think it skreens up the read me a bit. Will have to look at something neater

2021-06-23 08:06 UTC, closed without merging

2021-06-24 03:29 UTC, OIVAS7572 commented
Some of the changes by @lidevelopers  is Good